HH-112983 Init and add interal rule
hhru/eslint-plugin-import-rules pull request #1
Opened 2020-07-23 15:36 UTC by vkruglikov

инициализация проекта и добавил первое правило

2020-07-24 09:23 UTC, iliaaw requested changes

2020-07-24 09:23 UTC, ilyakhokhryakov commented on .babelrc
> +  "presets": [ "es2015-argon" ],
почему не preset-env

2020-07-24 09:23 UTC, ilyakhokhryakov commented on .babelrc
> +  "retainLines": true
зачем

2020-07-24 09:23 UTC, ilyakhokhryakov commented on .babelrc
> +}
настрой редактор чтобы вот этих «no newline at end of file» не было

2020-07-24 09:23 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +        const pathRegexps = (options.paths || []).map(p => new RegExp(p))
не используем сокращения

2020-07-24 09:23 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +        const normalizeSep = (somePath) => {
в https://nodejs.org/api/path.html ничего подходящего нет?

2020-07-24 09:23 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +            if (!expression) return false;
предлагаю https://github.com/hhru/eslint-config-hh подключить для этой репы

2020-07-24 09:23 UTC, ilyakhokhryakov commented
тесты планируются?

2020-07-24 10:09 UTC, vkruglikov commented on .babelrc
> +  "retainLines": true
чтобы легче дебажить

2020-07-24 10:10 UTC, vkruglikov commented on src/rules/no-internal-modules.js
> +            if (!expression) return false;
можно по подробнее. Не понял

2020-07-24 10:11 UTC, vkruglikov commented on src/rules/no-internal-modules.js
> +        const pathRegexps = (options.paths || []).map(p => new RegExp(p))
сокращения это `p` ?

2020-07-24 10:13 UTC, vkruglikov commented on .babelrc
> +  "presets": [ "es2015-argon" ],
Все необходимые зависимости
https://github.com/benmosher/babel-preset-es2015-argon/blob/master/index.js

+ используется в https://github.com/benmosher/eslint-plugin-import/blob/master/.babelrc#L2 , а я старался делать обращая внимание на этот плагин

2020-07-24 10:14 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +            if (!expression) return false;
мы тело ифов оборачиваем в фигурные скобки. и чтобы на такие вещи не тратить время на ревью, я предлагаю воспользоваться нашим конфигом еслинта.

2020-07-24 10:14 UTC, vkruglikov commented on src/rules/no-internal-modules.js
> +        const normalizeSep = (somePath) => {
кажется https://nodejs.org/api/path.html#path_path_normalize_path подхожит. 
Если критично посмотрю/поправлю

2020-07-24 10:15 UTC, vkruglikov commented
> тесты планируются?

Вообще не планировал. Нужно ли ? правило незначительное

2020-07-24 10:16 UTC, vkruglikov commented on src/rules/no-internal-modules.js
> +            if (!expression) return false;
понял. ок

2020-07-24 10:19 UTC, ilyakhokhryakov commented on .babelrc
> +  "retainLines": true
так ты уже задебажил? для релиза не нужно?

2020-07-24 10:19 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +        const pathRegexps = (options.paths || []).map(p => new RegExp(p))
да

2020-07-24 10:20 UTC, ilyakhokhryakov commented on src/rules/no-internal-modules.js
> +        const normalizeSep = (somePath) => {
критично, зачем стандартную библиотеку дублировать

2020-07-24 10:20 UTC, vkruglikov commented on src/rules/no-internal-modules.js
> +        const pathRegexps = (options.paths || []).map(p => new RegExp(p))
ок

2020-07-24 10:22 UTC, vkruglikov commented on .babelrc
> +  "retainLines": true
можно убрать, но так как это все же плагин для разработки, думаю было бы полезно увидеть ошибку в консоли (если она будет)  с плюс минус той же строкой

2020-07-24 10:24 UTC, ilyakhokhryakov commented
у нас все остальные плагины тестами покрыты

2020-07-27 11:57 UTC, iliaaw approved these changes

2020-07-27 12:03 UTC, merged